### ISSUE TITLE
Issues converting from isyntax2raw pipeline

### ISSUE THREAD

**Issue by djdeiter** [glencoesoftware/raw2ometiff#12]
Hi, glad to see you guys doing great work in the battle for open pathology.

I can convert mrxs through the pipeline to ome-tiff, but I have yet to successfully get an isyntax image to make it out of raw2ometiff. I've tried on my linux system as well as win10, throws the same error after I'd say 3/4 the tiles have been processed. Happens with images from my scanner as well as example images from phillips site. Doesn't appear to be any issue with isyntax2raw.

Console output:
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@26adfd2d): java.lang.NullPointerException
        at picocli.CommandLine.execute(CommandLine.java:1180)
        at picocli.CommandLine.access$800(CommandLine.java:141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
        at picocli.CommandLine.call(CommandLine.java:1786)
        at picocli.CommandLine.call(CommandLine.java:1710)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:260)
Caused by: java.lang.NullPointerException
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.getInputTileBytes(PyramidFromDirectoryWriter.java:361)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.convertToPyramid(PyramidFromDirectoryWriter.java:651)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:284)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:97)
        at picocli.CommandLine.execute(CommandLine.java:1173)
        ... 8 more
```

**Comment by melissalinkert** [comment]
Thanks for the feedback, @djdeiter.  I'd expect this problem to be fixed with https://github.com/glencoesoftware/raw2ometiff/pull/11, assuming you're using https://github.com/glencoesoftware/isyntax2raw/tree/v0.2.0rc1 to convert the .isyntax files.

**Comment by djdeiter** [comment]
@melissalinkert That fix did the trick, thanks.
