### ISSUE TITLE
JPEG compression issue

### ISSUE THREAD

**Issue by douglasrennick** [glencoesoftware/raw2ometiff#22]
Using latest versions of raw2ometiff and isyntax2raw, JPEG compression option cuts off portions of images converted from iSyntax format - occurs on 1.isyntax and 3.isyntax but not on 2.isyntax or 6.isyntax. Other compression options do not result in this problem

3.isyntax after JPEG compression:
![3 isyntax - JPEG Compression Issue](https://user-images.githubusercontent.com/56600503/80507864-3d3cee80-896f-11ea-86b6-71cf2a3dfe55.PNG)

**Comment by melissalinkert** [comment]
I can reproduce using https://github.com/glencoesoftware/isyntax2raw/pull/15 and https://github.com/glencoesoftware/raw2ometiff/pull/20.  A bunch of exceptions like this are logged to stderr:

```
Exception in thread "pool-1-thread-1" java.lang.ArrayIndexOutOfBoundsException: 68096
  at java.awt.image.DataBufferByte.getElem(DataBufferByte.java:256)
  at java.awt.image.BandedSampleModel.getPixels(BandedSampleModel.java:436)
  at java.awt.image.Raster.getPixels(Raster.java:1580)
  at java.awt.image.BufferedImage.setData(BufferedImage.java:1533)
  at ome.codecs.gui.AWTImageTools.constructImage(AWTImageTools.java:631)
  at ome.codecs.gui.AWTImageTools.constructImage(AWTImageTools.java:569)
  at ome.codecs.gui.AWTImageTools.makeImage(AWTImageTools.java:335)
  at ome.codecs.gui.AWTImageTools.makeImage(AWTImageTools.java:119)
  at ome.codecs.gui.AWTImageTools.makeImage(AWTImageTools.java:193)
  at ome.codecs.gui.AWTImageTools.makeImage(AWTImageTools.java:448)
  at ome.codecs.JPEGCodec.compress(JPEGCodec.java:80)
  at loci.formats.codec.WrappedCodec.compress(WrappedCodec.java:63)
  at loci.formats.codec.JPEGCodec.compress(JPEGCodec.java:52)
  at loci.formats.tiff.TiffCompression.compress(TiffCompression.java:356)
  at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.writeTile(PyramidFromDirectoryWriter.java:934)
  at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.lambda$convertToPyramid$0(PyramidFromDirectoryWriter.java:634)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

Probably that's incorrect XY dimensions being passed to the codec for edge tiles, which won't make a difference for LZW or uncompressed.

**Comment by melissalinkert** [comment]
I'd expect https://github.com/glencoesoftware/raw2ometiff/pull/20/commits/df644f97ff72ee0948c81dabd07e8258ac5d3795 on #20 to fix this issue.

**Comment by melissalinkert** [comment]
@douglasrennick : OK to close now that #20 is merged, or are there still problems with JPEG compression?

**Comment by douglasrennick** [comment]
JPEG compression issues have been resolved with the merge. Closing issue.
