### ISSUE TITLE
Could not create an N5 reader

### ISSUE THREAD

**Issue by Mohammedhusen** [glencoesoftware/raw2ometiff#35]
Hi Team,

While converting bioformats2raw to raw2ometiff am getting this error, could you please help.

Command:

sh raw2ometiff data.n5/ s3.tif 

Error :

2020-06-11 12:48:38,372 [main] INFO  org.perf4j.TimingLogger - start[1591868918370] time[0] tag[initialize]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@309e345f): java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at picocli.CommandLine.executeUserObject(CommandLine.java:1792)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
	at picocli.CommandLine.call(CommandLine.java:2560)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:243)
Caused by: java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:274)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:86)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	... 9 more
Caused by: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.initialize(PyramidFromDirectoryWriter.java:460)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:260)
	... 11 more

**Comment by melissalinkert** [comment]
The input tile directory for ```raw2ometiff``` should be a directory that contains a ```data.n5``` directory, not ```data.n5``` itself.  It should be the same as the output directory used when running ```bioformats2raw```.

**Comment by Mohammedhusen** [comment]
@melissalinkert ,

Thanks for your quick response, that solved the issue.
