### ISSUE TITLE
Large 3D volumes hang on RandomAccessFile.setLength

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/raw2ometiff#49]
Generating an OME-TIFF from an IMS that's `1024^3 (t=512, c=2)` hangs on setLength. Changing the ending (e.g., to `.ome.btf`) doesn't seem to change the behavior.

```
"main" glencoesoftware/bioformats2raw#1 prio=5 os_prio=0 tid=0x00007fb91000c000 nid=0x15 runnable [0x00007fb915852000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.setLength(Native Method)
        at loci.common.NIOFileHandle.setLength(NIOFileHandle.java:229)
        at loci.common.AbstractNIOHandle.validateLength(AbstractNIOHandle.java:87)
        at loci.common.NIOFileHandle.writeSetup(NIOFileHandle.java:659)
        at loci.common.NIOFileHandle.writeLong(NIOFileHandle.java:597)
        at loci.common.RandomAccessOutputStream.writeLong(RandomAccessOutputStream.java:326)
        at loci.formats.tiff.TiffSaver.writeIntValue(TiffSaver.java:968)
        at loci.formats.tiff.TiffSaver.writeIFDValue(TiffSaver.java:606)
        at loci.formats.tiff.TiffSaver.writeIFD(TiffSaver.java:531)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.writeIFD(PyramidFromDirectoryWriter.java:866)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.writeIFDs(PyramidFromDirectoryWriter.java:640)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.convertToPyramid(PyramidFromDirectoryWriter.java:502)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:211)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:89)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
        at picocli.CommandLine.call(CommandLine.java:2560)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:189)
```

**Comment by sbesson** [comment]
From a Zarr fileset generated using `bioformats2raw "test&sizeX=56&sizeY=56&sizeZ=1024&sizeT=51.fake" --file_type zarr --compression raw zarr`, I measured the time taken for writing IFDs in various situations:

- local machine / local disk: 2min
- remote server / local disk: 12min
- remote server / NFS: > 25 min (and still writing)

**Comment by joshmoore** [comment]
Looks like it's just GPFS on the one server. 🤦🏼

**Comment by chris-allan** [comment]
Safe to close this as a filesystem problem now, @joshmoore?

**Comment by joshmoore** [comment]
@chris-allan: I _think_ so. I should note that now a **second** server has hung after running this code for an external period of time. That could still point to an underlying hardware issue, but I haven't heard back yet. Happy to re-close under that assumption and I can always re-open if I see it elsewhere. I *do* wonder what's going on under the hood though. :wink:
