### ISSUE TITLE
Cannot convert

### ISSUE THREAD

**Issue by ozgurpolat** [glencoesoftware/raw2ometiff#51]
Hi;

I successfully converted my image from isyntax to raw using "philips-pathologysdk-1.2.1-windows10-py37-research.zip" and "https://github.com/glencoesoftware/isyntax2raw/releases/tag/v0.3.1". Now I have a folder named data.h5 and two files "METADATA.json" and "METADATA.ome.xml" in a folder named "38GX8_HE_20210301_091438". When I try to convert these to ome.tiff using this command:

`./raw2ometiff /media/sf_sandbox/38GX8_HE_20210301_091438 38GX8_HE_20210301_091438.ome.tiff`

I get this error:

`Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@5e316c74): java.lang.RuntimeException: loci.formats.FormatException: Could not create a reader`

[SUCCESFUL CONVERSION TO RAW]
isyntax2raw write_tiles 38GX8_HE_20210301_091438.isyntax 38GX8_HE_20210301_091438
/home/ozgur/anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/zarr/n5.py:419: RuntimeWarning: Not all N5 implementations support blosc compression (yet). You might not be able to open the dataset with another N5 library.
  RuntimeWarning
2021-03-19 02:18:16,406 INFO    [     isyntax2raw] (140277820462912) wrote LABELIMAGE image
2021-03-19 02:18:23,696 INFO    [     isyntax2raw] (140277820462912) wrote MACROIMAGE image
2021-03-19 02:18:23,716 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[0, 1, 92677], [0, 1, 89605], [0, 1, 2]]
2021-03-19 02:18:23,717 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 182
2021-03-19 02:18:23,717 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 176
2021-03-19 03:01:21,287 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[2, 2, 92674], [2, 2, 89602], [0, 1, 2]]
2021-03-19 03:01:21,287 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 91
2021-03-19 03:01:21,288 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 88
2021-03-19 03:13:18,039 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[8, 4, 92668], [8, 4, 89596], [0, 1, 2]]
2021-03-19 03:13:18,039 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 46
2021-03-19 03:13:18,039 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 44
2021-03-19 03:17:14,696 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[16, 8, 92656], [16, 8, 89584], [0, 1, 2]]
2021-03-19 03:17:14,696 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 23
2021-03-19 03:17:14,697 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 22
2021-03-19 03:17:36,780 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[32, 16, 92640], [32, 16, 89568], [0, 1, 2]]
2021-03-19 03:17:36,780 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 12
2021-03-19 03:17:36,780 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 11
2021-03-19 03:17:44,765 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[64, 32, 92608], [64, 32, 89536], [0, 1, 2]]
2021-03-19 03:17:44,765 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 6
2021-03-19 03:17:44,765 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 6
2021-03-19 03:17:45,499 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[128, 64, 92544], [128, 64, 89472], [0, 1, 2]]
2021-03-19 03:17:45,499 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 3
2021-03-19 03:17:45,499 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 3
2021-03-19 03:17:45,716 INFO    [     isyntax2raw] (140277820462912) dimension ranges = [[256, 128, 92416], [256, 128, 89344], [0, 1, 2]]
2021-03-19 03:17:45,716 INFO    [     isyntax2raw] (140277820462912) # of X (512) tiles = 2
2021-03-19 03:17:45,716 INFO    [     isyntax2raw] (140277820462912) # of Y (512) tiles = 2

[ERROR]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@5e316c74): java.lang.RuntimeException: loci.formats.FormatException: Could not create a reader
	at picocli.CommandLine.executeUserObject(CommandLine.java:1792)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
	at picocli.CommandLine.call(CommandLine.java:2560)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:203)
Caused by: java.lang.RuntimeException: loci.formats.FormatException: Could not create a reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:232)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:92)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	... 9 more
Caused by: loci.formats.FormatException: Could not create a reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.initialize(PyramidFromDirectoryWriter.java:357)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:218)
	... 11 more

**Comment by melissalinkert** [comment]
Which version of raw2ometiff are you using?  0.2.8 still supports converting from n5 to OME-TIFF, but the current ```master``` branch does not support n5, only Zarr (see #47).

**Comment by ozgurpolat** [comment]
Hi Melissa, thank you for the quick response. I solved the problem. I have isyntax file which needs to be converted to raw format using isyntax2raw first. But I was getting 

`"ModuleNotFoundError: No module named 'pixelengine'" error. `

I saw your message in https://forum.image.sc/t/isyntax2raw-issue/41913 which says:

" isyntax2raw is expected to work with 1.2.1; we have not yet released a version that is known to work with 2.0."

so I decided to downgrade Philips Pathology SDK from 2.0 to 1.2.1. But this did not fix the problem. I was still getting the same error. A collogue of mine told me what the problem was. We spend couple of days trying to find a solution. Basically when  Philips Pathology SDK installs, it puts pixelengine and some other dependencies in /usr/lib/python3/dist-packages folder and if you are using a conda environment, these packages are not available so I copied the following packages from /usr/lib/python3/site-packages/ folder to the python folder in my anaconda.

{FROM]
/usr/lib/python3/dist-packages/pixelengine-2.2.11.egg-info
/usr/lib/python3/dist-packages/eglrendercontext-2.2.11.egg-info
/usr/lib/python3/dist-packages/gles2renderbackend-2.2.11.egg-info
/usr/lib/python3/dist-packages/gles3renderbackend-2.2.11.egg-info
/usr/lib/python3/dist-packages/softwarerenderbackend-2.2.11.egg-info
/usr/lib/python3/dist-packages/softwarerendercontext-2.2.11.egg-info
/usr/lib/python3/dist-packages/softwarerenderbackend.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/softwarerendercontext.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/pixelengine.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/gles2renderbackend.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/gles3renderbackend.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/eglrendercontext.cpython-36m-x86_64-linux-gnu.so

[TO]
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/eglrendercontext-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/gles2renderbackend-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/gles3renderbackend-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/pixelengine-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/softwarerenderbackend-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/softwarerendercontext-2.2.11.egg-info
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/softwarerenderbackend.cpython-36m-x86_64-linux-gnu.so
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/softwarerendercontext.cpython-36m-x86_64-linux-gnu.so
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/pixelengine.cpython-36m-x86_64-linux-gnu.so
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/gles2renderbackend.cpython-36m-x86_64-linux-gnu.so
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/gles3renderbackend.cpython-36m-x86_64-linux-gnu.so
../anaconda3/envs/isyntax2raw/lib/python3.6/site-packages/eglrendercontext.cpython-36m-x86_64-linux-gnu.so

Once these files are copied, I can do the conversion to raw. However this only fixes half of the problem, the other problem was I was still using SDK 1.2.1. So I had to reinstall SDK 2.0 and copy the files above once more from ubuntu python folder to my anaconda python folder, then I was able to use raw2ometiff and do the conversion from raw to ome.tiff format.
