### ISSUE TITLE
--version throws a NullPointer Exception

### ISSUE THREAD

**Issue by stick** [glencoesoftware/raw2ometiff#77]
--help lists --version as a print version option
--version produces a NullPointerException when used.

```
raw2ometiff/bin/raw2ometiff --help
Missing required parameters: <inputDirectory>, <outputFilePath>
Usage: <main class> [-p] [--legacy] [--rgb] [--version] [--debug[=<logLevel>]]
                    [--compression=<compression>] [--max_workers=<maxWorkers>]
                    [--quality=<compressionQuality>] <inputDirectory>
                    <outputFilePath>
      <inputDirectory>   Directory containing pixel data to convert
      <outputFilePath>   Relative path to the output OME-TIFF file
      --compression=<compression>
                         Compression type for output OME-TIFF file
                           (Uncompressed, LZW, JPEG-2000, JPEG-2000 Lossy,
                           JPEG, zlib; default: LZW)
      --debug, --log-level[=<logLevel>]
                         Change logging level; valid values are OFF, ERROR,
                           WARN, INFO, DEBUG, TRACE and ALL. (default: WARN)
      --legacy           Write a Bio-Formats 5.9.x pyramid instead of OME-TIFF
      --max_workers=<maxWorkers>
                         Maximum number of workers (default: 16)
      --quality=<compressionQuality>
                         Compression quality
      --rgb              Attempt to write channels as RGB; channel count must
                           be 3
  -p, --progress         Print progress bars during conversion
      --version          Print version information and exit
```

```
raw2ometiff/bin/raw2ometiff --version
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@1677d1): java.lang.NullPointerException
        at picocli.CommandLine.executeUserObject(CommandLine.java:1792)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
        at picocli.CommandLine.call(CommandLine.java:2560)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:210)
Caused by: java.lang.NullPointerException
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:216)
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:97)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        ... 9 more
```

**Comment by melissalinkert** [comment]
This should have been fixed by #75, which will be in the next released version.
